spring.application.name=VirtualWallet

app.base-url=http://localhost:8080

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

application.security.jwt.secret-key=${JWT_SECRET_KEY}
application.security.jwt.expiration=${JWT_EXPIRATION}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

app.transaction.large-amount-threshold=1000
app.cron.recurring-transactions=0 0 10 * * ?

app.bank.dummy.deposit-delay-ms=1000
app.bank.dummy.withdrawal-delay-ms=1500
app.bank.dummy.success-rate-deposit=0.1
app.bank.dummy.success-rate-withdrawal=0.05

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html